import cv2

tablero = cv2.imread('tableroejemplo.jpeg')
if tablero is None:
    raise FileNotFoundError("No se cargó la imagen, revisa la ruta")
tablerogris = cv2.cvtColor(tablero, cv2.COLOR_BGR2GRAY)
tableroblur = cv2.GaussianBlur(tablerogris, (9, 9), 0)
canny = cv2.Canny(tableroblur, 50,150)
contornos, _ = cv2.findContours(canny, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
mas_grande = max(contornos, key=cv2.contourArea)
tablero_contorno = tablero.copy()
cv2.drawContours(tablero_contorno, [mas_grande], -1, (0, 255, 0), 3)
perimetro = cv2.arcLength(mas_grande, True)
aprox = cv2.approxPolyDP(mas_grande, 0.02 * perimetro, True)
print(f"Vertices detectados: {len(aprox)}")
cv2.imshow("Contorno", tablero_contorno)
cv2.imshow("Tablero",tablerogris)
cv2.imshow("TableroBlur",tableroblur)
cv2.imshow("Canny",canny)
tablero_final = tablero.copy()
cv2.drawContours(tablero_final, [aprox], -1, (0, 255, 0), 3)
cv2.imshow("Final", tablero_final)
cv2.waitKey(0)
cv2.destroyAllWindows()
